[package]
name = "pipewire-ao-sys"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
links = "pipewire-ao-0.3"
categories.workspace = true
description = "Rust FFI bindings for PipeWireAO"
license.workspace = true
readme = "README.md"
keywords = ["ffi", "pipewire", "adaptive-optics", "realtime"]

[dependencies]
spa_sys.workspace = true

[build-dependencies]
bindgen = { workspace = true, features = ["runtime"] }
system-deps.workspace = true

[package.metadata.system-deps]
libpipewire = { name = "libpipewire-ao-0.3", version = "0.3" }

[lib]
name = "pipewire_sys"
doctest = false # https://github.com/rust-lang/rust-bindgen/issues/1313
