[package]
name = "libspa-ao-sys"
version.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true
links = "libspa-ao-0.2"
categories.workspace = true
description = "Rust FFI bindings for PipeWireAO SPA"
license.workspace = true
readme = "README.md"
keywords = ["ffi", "pipewire", "adaptive-optics", "realtime"]

[dependencies]

[build-dependencies]
bindgen = { workspace = true, features = ["experimental", "runtime"] }
cc.workspace = true
system-deps.workspace = true

[package.metadata.system-deps]
libspa = { name = "libspa-ao-0.2", version = "0.2" }
libpipewire = { name = "libpipewire-ao-0.3", version = "0.3" }

[lib]
name = "libspa_sys"
doctest = false # https://github.com/rust-lang/rust-bindgen/issues/1313

[features]
v0_3_65 = []
